### PR TITLE
change neck joints to revolute and fix some typos

### PR DESCRIPTION
**Pull request by youngsunkim**

### CODE REVIEW

**Review by jslee02 — DISMISSED** [review]

**Comment by brianhou** [comment]
The following patch is an uncommitted change on `herb2`, which I think corresponds to setting the neck tilt to -30 degrees instead of -40 degrees. @yskim041, can you confirm and bundle this change into this PR?

```patch
diff --git a/robots/herb_base.urdf.xacro b/robots/herb_base.urdf.xacro
index 33ac0c7..5d22a87 100644
--- a/robots/herb_base.urdf.xacro
+++ b/robots/herb_base.urdf.xacro
@@ -233,7 +233,7 @@
           velocity="4.18879" />
       <origin
           xyz="0 0 -0.0919"
-          rpy="-0.698132 0 0" />
+          rpy="-0.523599 0 0" />
       <parent
           link="neck_pan" />
       <child
```

**Review by brianhou — CHANGES_REQUESTED** [review]
The following patch is an uncommitted change from `herb2_ws`, which I think corresponds to setting the neck tilt to -30 degrees instead of -40 degrees. @yskim041, can you confirm and bundle this change into this PR?

```patch
diff --git a/robots/herb_base.urdf.xacro b/robots/herb_base.urdf.xacro
index 33ac0c7..5d22a87 100644
--- a/robots/herb_base.urdf.xacro
+++ b/robots/herb_base.urdf.xacro
@@ -233,7 +233,7 @@
           velocity="4.18879" />
       <origin
           xyz="0 0 -0.0919"
-          rpy="-0.698132 0 0" />
+          rpy="-0.523599 0 0" />
       <parent
           link="neck_pan" />
       <child
```

**Comment by aditya-vk** [comment]
@jslee02 @yskim041  Is this PR still work in progress?

**Comment by brianhou** [comment]
Bump

**Comment by aditya-vk** [comment]
@brianhou: Ready for review. This allows for control of the neck.

**Review by brianhou — APPROVED** [review]

**Pull request merged**
