### PR TITLE
Fix the Self-Collision in the Model

### PR DESCRIPTION
**Pull request by aditya-vk**
This PR corrects the orientation of the kinect sensor in the model. 
1. The changes have been tested in *simulation* by running `pantry-loading`. 
2. The tests that have been failing as reported in  https://github.com/personalrobotics/libherb/issues/38 now successfully pass.

This change needs to be verified, still, on real hardware with actual perception.

### CODE REVIEW

**Comment by brianhou** [comment]
To be clear, we would merge this to resolve #41 instead of #42?

@yskim041, perhaps you can try this out to make sure the kinect frame is correct?

**Comment by aditya-vk** [comment]
@brianhou yeah, that's right. 

For simulation, this is currently alright, but we should verify by running perception (with @yskim041's help) on the real robot to ensure the object positions are detected properly with respect to the robot.

**Review by brianhou — APPROVED** [review]

**Comment by brianhou** [comment]
@yskim041 Let's merge this Friday after testing the full pipeline.

**Comment by jslee02** [comment]
@yskim041, @brianhou : Are we ready to merge this?

This is blocking https://github.com/personalrobotics/libherb/pull/67.

**Comment by brianhou** [comment]
No, we haven't tested this yet. We need to do this today.

**Comment by aditya-vk** [comment]
This has been tested and can be merged. It should immediately unblock personalrobotics/libherb#67.

**Pull request merged**
