### PR TITLE
added camera calibration data into herb description

### PR DESCRIPTION
**Pull request by pengjujin**

### CODE REVIEW

**Comment by Shushman** [comment]
I'm okay with everything except the weird folder name. I presume that was the timestamp or ID for the rosbag @pengjujin ? Could we rename the folder to something more sensible, or not have an inner folder at all?

**Comment by Shushman** [comment]
Ping! Remember to take care of this guys! @rachelholladay @pengjujin

**Comment by mkoval** [comment]
This directory structure is [required by `iai_kinect2`](https://github.com/code-iai/iai_kinect2/blob/master/kinect2_bridge/src/kinect2_bridge.cpp#L613). In that code `sensor` is the serial number (e.g. `502845441942`) of the device.

**Comment by Shushman** [comment]
Whoops! My bad then.

**Review by Shushman — APPROVED** [review]
The files look good to me

**Pull request merged**
