### PR TITLE
Change base link name

### PR DESCRIPTION
**Pull request by gilwoolee**
Changes base link's name to `base_footprint` to follow REP-120.

### CODE REVIEW

**Review by mkoval — APPROVED** [review]
Looks great! :+1: Thanks for making this change.

**Comment by jslee02** [comment]
How about adding a comment that we comply to REP-120 to `README.md` for later updates?

**Comment by gilwoolee** [comment]
Added the comment for REP-120. @mkoval @jslee02 Are we good to go? :D

**Review by jslee02 — APPROVED** [review]
Looks good to me. Thanks for adding the comment!

**Pull request merged**
